import os
import sys
import time
import json
import requests
import xml.etree.ElementTree as ET
from datetime import datetime, timedelta
from google import genai
from google.genai import errors

# ==========================================
# SYSTEM SETTINGS & SECRETS
# ==========================================
CHAT_ID = "-1004369470593"
RSS_URL = "https://nsearchives.nseindia.com/content/RSS/Online_announcements.xml"

TELEGRAM_TOKEN = os.getenv("TELEGRAM_TOKEN")
GH_PAT = os.getenv("GH_PAT")
GITHUB_REPOSITORY = os.getenv("GITHUB_REPOSITORY")

# Fetch all 3 keys from your updated environment variables
API_KEYS = [
    os.getenv("GEMINI_API_KEY_1"),
    os.getenv("GEMINI_API_KEY_2"),
    os.getenv("GEMINI_API_KEY_3")
]
# Filter out any keys that failed to load
API_KEYS = [k for k in API_KEYS if k]

if not API_KEYS:
    print("[❌ CRITICAL] No Gemini API keys found in environment variables!")
    sys.exit(1)

if not TELEGRAM_TOKEN:
    print("[❌ CRITICAL] TELEGRAM_TOKEN is missing!")
    sys.exit(1)

# Keep track of which key index to use next
current_key_index = 0
MEMORY_EXPIRY_HOURS = 6
processed_cache = {}

def get_next_client():
    """Rotates through the available keys sequentially to balance free-tier limits."""
    global current_key_index
    key = API_KEYS[current_key_index]
    # Point the index to the next key for the next run
    current_key_index = (current_key_index + 1) % len(API_KEYS)
    print(f"[🔄 Key Rotation] Using API Key Slot {current_key_index + 1} for this request.")
    return genai.Client(api_key=key)

def clean_expired_cache():
    now = datetime.now()
    expired_keys = [k for k, timestamp in processed_cache.items() if now - timestamp > timedelta(hours=MEMORY_EXPIRY_HOURS)]
    for k in expired_keys:
        del processed_cache[k]

def load_live_configs():
    try:
        with open("watchlist.json", "r") as f:
            return json.load(f)
    except Exception as e:
        print(f"[⚠️] Configuration load failed, falling back to defaults: {e}")
        return {
            "tracking_mode": "All Stocks (Default)",
            "selected_watchlist": [],
            "high_value_keywords": ["FINANCIAL RESULTS", "DIVIDEND"],
            "routine_keywords": ["SHAREHOLDING PATTERN"]
        }

def analyze_with_ai(headline, details):
    prompt = f"""
    Analyze the following Indian stock market filing:
    Headline: {headline}
    Details: {details}

    Format your output EXACTLY as: Category | Sentiment | Bulleted Summary
    Rules:
    1. Category: One from ["Business Update", "Routine", "Financial Results", "Credit Rating"]
    2. Sentiment: One from ["🟢 Positive", "⚪ Neutral", "🔴 Negative"]
    3. Summary: 2-3 short bullets starting with '-'. Clear facts only. No intro text.
    """
    
    # Try up to 3 times (once per key) if an authentication or rate limit error happens
    for attempt in range(len(API_KEYS)):
        try:
            client = get_next_client()
            response = client.models.generate_content(
                model='gemini-2.0-flash', 
                contents=prompt
            )
            
            if not response.text:
                return "Business Update", "⚪ Neutral", "- No response text generated by AI model."
                
            parts = response.text.strip().split('|')
            if len(parts) >= 3:
                return parts[0].strip(), parts[1].strip(), parts[2].strip()
            return "Business Update", "⚪ Neutral", f"- {response.text.strip()}"
            
        except errors.APIError as ae:
            print(f"[❌ API Error on Key Attempt {attempt + 1}] {ae}. Trying next key...")
            continue  # Fall through loop to try the next key
        except Exception as e:
            print(f"[⚠️ Exception on Key Attempt {attempt + 1}] {e}. Trying next key...")
            continue

    return "Routine", "⚪ Neutral", "- All 3 rotated Gemini keys failed to authenticate or execute."

def send_telegram_message(text):
    url = f"https://api.telegram.org/bot{TELEGRAM_TOKEN}/sendMessage"
    payload = {"chat_id": CHAT_ID, "text": text, "parse_mode": "Markdown"}
    try:
        res = requests.post(url, json=payload, timeout=8)
        if res.status_code != 200:
            print(f"[-] Telegram target rejected payload: {res.text}")
    except Exception as e:
        print(f"[-] Telegram dispatch network error: {e}")

def check_feed_cycle(is_baseline=False):
    configs = load_live_configs()
    tracking_mode = configs.get("tracking_mode", "All Stocks (Default)")
    watchlist = [s.upper() for s in configs.get("selected_watchlist", [])]
    
    headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"}
    try:
        response = requests.get(RSS_URL, headers=headers, timeout=10)
        if response.status_code != 200:
            print(f"[⚠️] RSS stream unavailable: HTTP {response.status_code}")
            return
        
        root = ET.fromstring(response.content)
        items = root.findall('.//item')
        
        for item in reversed(items):
            title = item.find('title').text if item.find('title') is not None else "UNKNOWN"
            link = item.find('link').text if item.find('link') is not None else ""
            desc = item.find('description').text if item.find('description') is not None else ""
            pub_date = item.find('pubDate').text if item.find('pubDate') is not None else ""
            
            unique_key = f"{title}_{pub_date}"
            if unique_key in processed_cache:
                continue
                
            if is_baseline:
                processed_cache[unique_key] = datetime.now()
                continue
                
            matched = False
            if tracking_mode == "All Stocks (Default)":
                matched = True
            else:
                for symbol in watchlist:
                    if symbol in title.upper() or symbol in link.upper():
                        matched = True
                        break
            
            processed_cache[unique_key] = datetime.now()
            
            if not matched:
                continue
                
            print(f"[Match Found] Analyzing announcement: {title}")
            category, sentiment, ai_summary = analyze_with_ai(title, desc)
            
            clean_summary = ai_summary.replace("**", "").replace("*", "")
            
            message = (
                f"⚡ *Company:* {title}\n\n"
                f"📄 *Category:* {category} | {sentiment}\n\n"
                f"📝 *AI Summary:*\n{clean_summary}\n\n"
                f"⏰ *Time:* {pub_date}\n"
            )
            if link:
                message += f"📁 *Filing File:* [View Original Document]({link})"
                
            send_telegram_message(message)
            time.sleep(1)
            
    except Exception as e:
        print(f"[⚠️] Error during feed processing cycle loop: {e}")

def trigger_workflow_handover():
    if not GH_PAT or not GITHUB_REPOSITORY:
        print("[Handover] GitHub settings missing. Stopping loop pipeline.")
        return
        
    url = f"https://api.github.com/repos/{GITHUB_REPOSITORY}/actions/workflows/run.yml/dispatches"
    headers = {
        "Authorization": f"token {GH_PAT}",
        "Accept": "application/vnd.github.v3+json"
    }
    try:
        res = requests.post(url, json={"ref": "main"}, headers=headers, timeout=10)
        if res.status_code == 204:
            print("[🚀] Handover process chain successfully dispatched worker successor.")
            sys.exit(0)
        else:
            print(f"[❌] Handoff runner deployment failed: {res.status_code} - {res.text}")
    except Exception as e:
        print(f"[❌] Fatal link failure during handover transition: {e}")

if __name__ == "__main__":
    print(f"[🔥] Launching Action Monitor System Node: {datetime.now()}")
    
    print("[Sync] Building tracking indexing baseline...")
    check_feed_cycle(is_baseline=True)
    print(f"[Sync] Complete. Indexed {len(processed_cache)} elements.")
    
    RUN_DURATION = 21000  
    CHECK_INTERVAL = 10     
    start_time = time.time()
    loop_count = 0
    
    while time.time() - start_time < RUN_DURATION:
        loop_count += 1
        if loop_count % 30 == 0:
            clean_expired_cache()
            
        check_feed_cycle(is_baseline=False)
        time.sleep(CHECK_INTERVAL)
        
    print("[⏰] Window limit reached. Initiating script handoff relay chain...")
    trigger_workflow_handover()
