import os
import sys
import time
import json
import requests
import xml.etree.ElementTree as ET
from datetime import datetime, timedelta
from openai import OpenAI

# ==========================================
# SYSTEM SETTINGS & SECRETS
# ==========================================
CHAT_ID = "-1004369470593"
RSS_URL = "https://nsearchives.nseindia.com/content/RSS/Online_announcements.xml"
GROQ_MODEL = "llama-3.1-8b-instant"  # 14,400 requests/day free tier
GROQ_BASE_URL = "https://api.groq.com/openai/v1"

TELEGRAM_TOKEN = os.getenv("TELEGRAM_TOKEN")
GH_PAT = os.getenv("GH_PAT")
GITHUB_REPOSITORY = os.getenv("GITHUB_REPOSITORY")

# Fetch all 3 keys from your updated environment variables
API_KEYS = [
    os.getenv("GROQ_API_KEY_1"),
    os.getenv("GROQ_API_KEY_2"),
    os.getenv("GROQ_API_KEY_3")
]
# Filter out any keys that failed to load
API_KEYS = [k for k in API_KEYS if k]

if not API_KEYS:
    print("[❌ CRITICAL] No Groq API keys found in environment variables!")
    sys.exit(1)

if not TELEGRAM_TOKEN:
    print("[❌ CRITICAL] TELEGRAM_TOKEN is missing!")
    sys.exit(1)

# Keep track of which key index to use next
current_key_index = 0
MEMORY_EXPIRY_HOURS = 6
processed_cache = {}

def get_next_client():
    """Rotates through the available keys sequentially to balance free-tier limits."""
    global current_key_index
    key = API_KEYS[current_key_index]
    current_key_index = (current_key_index + 1) % len(API_KEYS)
    print(f"[🔄 Key Rotation] Using API Key Slot {current_key_index + 1} for this request.")
    return OpenAI(api_key=key, base_url=GROQ_BASE_URL)

def clean_expired_cache():
    now = datetime.now()
    expired_keys = [k for k, timestamp in processed_cache.items() if now - timestamp > timedelta(hours=MEMORY_EXPIRY_HOURS)]
    for k in expired_keys:
        del processed_cache[k]

def load_live_configs():
    try:
        with open("watchlist.json", "r") as f:
            return json.load(f)
    except Exception as e:
        print(f"[⚠️] Configuration load failed, falling back to defaults: {e}")
        return {
            "tracking_mode": "All Stocks (Default)",
            "selected_watchlist": [],
            "high_value_keywords": ["FINANCIAL RESULTS", "DIVIDEND"],
            "routine_keywords": ["SHAREHOLDING PATTERN"]
        }

def split_headline(desc):
    """Splits the RSS description into a subject line and a detail line.
    NSE feed format is: "<detail text> |SUBJECT: <category/subject text>"
    """
    if not desc:
        return "N/A", ""
    if "|SUBJECT:" in desc:
        detail, subject = desc.split("|SUBJECT:", 1)
        return subject.strip(), detail.strip()
    return desc.strip(), ""

def analyze_with_ai(headline, details):
    prompt = f"""
    Analyze the following Indian stock market filing:
    Headline: {headline}
    Details: {details}

    Format your output EXACTLY as: Category | Sentiment | Bulleted Summary
    Rules:
    1. Category: One from ["Business Update", "Routine", "Financial Results", "Credit Rating"]
    2. Sentiment: One from ["🟢 Positive", "⚪ Neutral", "🔴 Negative"]
    3. Summary: EXACTLY 3-4 bullet points, each on its own line, each starting with '-'.
       Each bullet should be a clear, standalone fact (dates, figures, names, actions).
       Do NOT repeat the Category or Sentiment inside the summary bullets.
       No intro text, no closing text, no markdown bold.
    """

    for attempt in range(len(API_KEYS)):
        try:
            client = get_next_client()
            response = client.chat.completions.create(
                model=GROQ_MODEL,
                messages=[{"role": "user", "content": prompt}]
            )

            text = response.choices[0].message.content if response.choices else None

            if not text:
                return "Business Update", "⚪ Neutral", "- No response text generated by AI model."

            parts = text.strip().split('|')
            if len(parts) >= 3:
                return parts[0].strip(), parts[1].strip(), parts[2].strip()
            return "Business Update", "⚪ Neutral", f"- {text.strip()}"

        except Exception as e:
            print(f"[⚠️ Exception on Key Attempt {attempt + 1}] {e}. Trying next key...")
            continue

    return "Routine", "⚪ Neutral", "- All rotated Groq keys failed to authenticate or execute."

def send_telegram_message(text):
    url = f"https://api.telegram.org/bot{TELEGRAM_TOKEN}/sendMessage"
    payload = {"chat_id": CHAT_ID, "text": text, "parse_mode": "Markdown"}
    try:
        res = requests.post(url, json=payload, timeout=8)
        if res.status_code != 200:
            print(f"[-] Telegram target rejected payload: {res.text}")
    except Exception as e:
        print(f"[-] Telegram dispatch network error: {e}")

def check_feed_cycle(is_baseline=False):
    configs = load_live_configs()
    tracking_mode = configs.get("tracking_mode", "All Stocks (Default)")
    watchlist = [s.upper() for s in configs.get("selected_watchlist", [])]

    headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"}
    try:
        response = requests.get(RSS_URL, headers=headers, timeout=10)
        if response.status_code != 200:
            print(f"[⚠️] RSS stream unavailable: HTTP {response.status_code}")
            return

        root = ET.fromstring(response.content)
        items = root.findall('.//item')

        for item in reversed(items):
            title = item.find('title').text if item.find('title') is not None else "UNKNOWN"
            link = item.find('link').text if item.find('link') is not None else ""
            desc = item.find('description').text if item.find('description') is not None else ""
            pub_date = item.find('pubDate').text if item.find('pubDate') is not None else ""

            unique_key = f"{title}_{pub_date}"
            if unique_key in processed_cache:
                continue

            if is_baseline:
                processed_cache[unique_key] = datetime.now()
                continue

            matched = False
            if tracking_mode == "All Stocks (Default)":
                matched = True
            else:
                for symbol in watchlist:
                    if symbol in title.upper() or symbol in link.upper():
                        matched = True
                        break

            processed_cache[unique_key] = datetime.now()

            if not matched:
                continue

            print(f"[Match Found] Analyzing announcement: {title}")

            headline_subject, headline_detail = split_headline(desc)
            category, sentiment, ai_summary = analyze_with_ai(headline_subject, headline_detail)

            clean_summary = ai_summary.replace("**", "").replace("*", "")

            doc_text = f"[View PDF Document]({link})" if link else "No Document"

            message = (
                f"🚨 *NEW NSE ANNOUNCEMENT* 🚨\n\n"
                f"⚡ *Company:* {title}\n\n"
                f"⏰ *Published:* {pub_date}\n\n"
                f"📄 *Category:* {category} | {sentiment}\n\n"
                f"📝 *Headline:* {headline_subject}\n"
                f">> {headline_detail}\n\n"
                f"📝 *AI Summary:* \n{clean_summary}\n\n"
                f"📎 *Filing Document:* {doc_text}"
            )

            send_telegram_message(message)
            time.sleep(1)

    except Exception as e:
        print(f"[⚠️] Error during feed processing cycle loop: {e}")

def trigger_workflow_handover():
    if not GH_PAT or not GITHUB_REPOSITORY:
        print("[Handover] GitHub settings missing. Stopping loop pipeline.")
        return

    url = f"https://api.github.com/repos/{GITHUB_REPOSITORY}/actions/workflows/run.yml/dispatches"
    headers = {
        "Authorization": f"token {GH_PAT}",
        "Accept": "application/vnd.github.v3+json"
    }
    try:
        res = requests.post(url, json={"ref": "main"}, headers=headers, timeout=10)
        if res.status_code == 204:
            print("[🚀] Handover process chain successfully dispatched worker successor.")
            sys.exit(0)
        else:
            print(f"[❌] Handoff runner deployment failed: {res.status_code} - {res.text}")
    except Exception as e:
        print(f"[❌] Fatal link failure during handover transition: {e}")

if __name__ == "__main__":
    print(f"[🔥] Launching Action Monitor System Node: {datetime.now()}")

    print("[Sync] Building tracking indexing baseline...")
    check_feed_cycle(is_baseline=True)
    print(f"[Sync] Complete. Indexed {len(processed_cache)} elements.")

    RUN_DURATION = 21000
    CHECK_INTERVAL = 10
    start_time = time.time()
    loop_count = 0

    while time.time() - start_time < RUN_DURATION:
        loop_count += 1
        if loop_count % 30 == 0:
            clean_expired_cache()

        check_feed_cycle(is_baseline=False)
        time.sleep(CHECK_INTERVAL)

    print("[⏰] Window limit reached. Initiating script handoff relay chain...")
    trigger_workflow_handover()
